apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: foodiesreplicaset
  labels:
    app: foodies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodies
      version: "1.0"
  template:
    metadata:
      labels:
        app: foodies
        version: "1.0"
    spec:
      containers:
        - name: foodies
          image: snehaiare/foodiesreplicaset:1.0
          resources:
            requests:
              cpu: "1"
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1024Mi
          ports:
            - name: tomcatport
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /foodies/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /foodies/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
            failureThreshold: 3